### ISSUE TITLE
CLJS logging and user-set *print-fn*

### ISSUE THREAD

**Issue by lorddoig** [ptaoussanis/encore#10]
I have a custom `*print-fn*` for my home-brewed logging system that adds a few things (date, time, namespace, etc).  The idea behind overriding `*print-fn*` instead of implementing it myself was so that I could add the same metadata when libraries try to print and save all this to a local file (I'm using node-webkit).  I'm using sente and it'd be mighty useful if encore would use `println` instead of going straight to the console.  Maybe a try/catch in `log->console` or making it dynamic would do it?  Didn't want to PR until I'd asked.

**Comment by ptaoussanis** [comment]
Hey, thanks for bringing this up.

Took a look at `*print-fn*` and not a fan; detecting the default binding is unnecessarily difficult+slow. 

In any case would like some more control over output, so have an experimental release up: `[com.taoensso/encore "1.21.0-SNAPSHOT"]`.

This exposes a new Encore-specific binding:
```clojure
  (enc-macros/defonce* ^:dynamic *log-fn*
    ^:default-fn ; Identifier for default log-fn
    (fn [{:keys [level msg_ raw-args]}]
      (case level
        :warn  (console-warn  [(str "WARN: "  @msg_)])
        :error (console-error [(str "ERROR: " @msg_)])
        :fatal (console-error [(str "FATAL: " @msg_)])
               (console-log   [               @msg_]))))
```

You can override that with any `(fn [{:keys [level msg_ raw-args]}])` that you'd like.
`level` is a keyword e/o `#{:trace :debug :info :warn :error :fatal :report}`.
`msg_` is a delayed formatted string.
`raw-args` is a seq of the raw logging args (i.e. before string formatting).

You could probably write a little util to adapt `*print-fn*`->`encore/*log-fn*` easily enough.

Let me know if that solves the issue for you? Cheers!

**Comment by ptaoussanis** [comment]
Closing this for now. Feel free to reopen if you have any issues with the current approach.

**Comment by lorddoig** [comment]
@ptaoussanis your "customer" service is second to none!  Thanks for this it's great, and sorry for leaving you hanging.  Very much looking forward to the day Timbre is clojurescript compatible.

**Comment by ptaoussanis** [comment]
No problem.

> Very much looking forward to the day Timbre is clojurescript compatible.

Actually not sure that there's anything to do besides what's already available in Encore. Is there something in particular you had in mind?

Appenders, middleware, rate limiting, etc. - none of that really makes sense for client-side logging.

**Comment by lorddoig** [comment]
Not especially, Encore does 99% of what you'd need.  I personally don't use it because my own half-baked library logs through the closure library which allows me to filter them off to files/remote endpoints when using node-webkit.

There's some cool stuff in `goog.debug.Log*` and friends e.g. [here](http://docs.closure-library.googlecode.com/git/class_goog_debug_Logger.html) that does quite a bit more than what `js/console` offers - buffers, filters, formatting, namespace hierarchies, different levels for different things, etc, etc (is there anything the closure lib doesn't do?) - might be worth having a look.

But then again maybe nobody actually needs this stuff!

Thanks again.

**Comment by ptaoussanis** [comment]
> There's some cool stuff in goog.debug.Log* and friends e.g. here that does quite a bit more than what js/console offers

Hmm, yeah - I've never personally had much of a need for any of that for client-side logging tbh. I'd be open to hearing ideas if folks had specific requirements that weren't being met, but barring that I wouldn't really expect to see much in Cljs Timbre support than what's already in Encore.

Definitely do feel free to let me know if you ever run into further issues though - things you want to do that you can't with Encore's current Cljs logging support, etc.

Cheers! :-)
