### ISSUE TITLE
Question on scoped functions

### ISSUE THREAD

**Issue by tuhlmann** [ptaoussanis/encore#13]
Hi Peter,

this is just a question on encore. I'm reading the code to learn more Clojure and ran across this block:

```
(let [logf* (fn [level fmt xs]
                (when (log-level-sufficient? level)
                  (*log-fn* {:level level :?fmt fmt :xs xs
                             :msg_ (delay (apply format fmt xs))})
                  nil))]
    (defn tracef  [fmt & xs] (logf* :trace  fmt xs))
    (defn debugf  [fmt & xs] (logf* :debug  fmt xs))
    (defn infof   [fmt & xs] (logf* :info   fmt xs))
    (defn warnf   [fmt & xs] (logf* :warn   fmt xs))
    (defn errorf  [fmt & xs] (logf* :error  fmt xs))
    (defn fatalf  [fmt & xs] (logf* :fatal  fmt xs))
    (defn reportf [fmt & xs] (logf* :report fmt xs))))
```

My question is, is there a way to access these functions defined inside such a block?

Thanks,
Torsten.

**Comment by ptaoussanis** [comment]
Hey Torsten, sure.

>  is there a way to access these functions defined inside such a block?

Anything in a `let` is accessible only within the `let` block, so the `logf*` fn here is only accessible to the block of `defn`s.

`def`/`defn` are different/special in that they'll always establish a _top-level_ var, regardless of the scope in which they occur. These define the same top-level var:
```clojure
(def my-var "foo") ; Defines my-ns/my-var

(let [foo-val "foo"]
  (def my-var foo-val)) ; Also defines my-ns/my-var
```

So the `tracef`...`reportf` fns are all accessible as usual through `encore/tracef`...`encore/reportf` (note that they're only defined in ClojureScript btw).

Does that make sense / answer your question?

**Comment by tuhlmann** [comment]
Hi Peter,

thanks for the explanation, makes perfect sense. I was expecting it to work that way. And it just failed to work in my code because I forgot to add the defined functions to the :require statement :)

Allow me two followup questions:

* You say this block in Encore is only defined in ClojureScript, which is fine. But the general principle of declaring def/defn inside a let and accessing them from outside also works in Clojure, right?

* I have changed my application to use the Component library. I'm still thinking of ways to supply the component map to API functions of that component. 
Would it be acceptable Clojure style to declare these API functions inside the scope that knows the component, i.e, from the start method?
What would happen with a defn if its defined twice (after a reset of the component system)? I would suspect they are overridden?

Awesome thanks,
Torsten.

**Comment by ptaoussanis** [comment]
> But the general principle of declaring def/defn inside a let and accessing them from outside also works in Clojure, right?

Yup, it'll work in Clojure and ClojureScript.

> Would it be acceptable Clojure style to declare these API functions inside the scope that knows the component, i.e, from the start method?

No, you'll definitely want to avoid that. `def`/`defn`s aren't something you'll want to call in the body of a function, etc.

You can call `def`/`defn` to redefine vars during REPL development, but you'll want the var defs to be fixed during production. If you want a value that can change during production (e.g. component state), then you'll want one of the ref types (like an `atom`), or a thread-local `binding`.

Does that make sense?

**Comment by tuhlmann** [comment]
@ptaoussanis Makes sense. I'm using an atom now to store the system map and then let the API functions access it.

Guess I'm missing the OO ways of captured state within a class :)

Thanks,
Torsten.

**Comment by ptaoussanis** [comment]
Closing this for now, feel free to reopen or post a new issue if you've got any follow up questions. Cheers :-)
