### ISSUE TITLE
Exception while compiling/running the REPL

### ISSUE THREAD

**Issue by jaju** [ptaoussanis/encore#16]
I experienced something strange today, and it took me quite some time to figure out a workaround. I'm not sure whose problem it is. The problem (as I explain below) seemed to appear without any good reason(s) I could think of. Previous versions - as I checked out from my git repo of my private project - which were working fine, threw up this error too!

Here's the relevant (I believe) portion from the stack trace on attempting to run "lein repl"
```
Caused by: java.lang.ClassNotFoundException: clojure.core.async.impl.channels.ManyToManyChannel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at clojure.lang.RT.classForName(RT.java:2154)
	at clojure.lang.RT.classForName(RT.java:2163)
	at taoensso.encore$chan_QMARK_.<clinit>(encore.clj:195)
```

As you can see, the class clojure.core.async.impl.channels.ManyToManyChannel isn't being found. I made the following change in encore.cljx (line 196) to force the class-loader to load this class
From:
```clojure
#+clj  (instance? clojure.core.async.impl.channels.ManyToManyChannel x)
```
To:
```clojure
#+clj  (do (Class/forName "clojure.core.async.impl.channels.ManyToManyChannel") (instance? clojure.core.async.impl.channels.ManyToManyChannel x))
```
That resolved the issue for me, and "lein repl" now works again.

I'm sorry if this is the wrong place - but the problem surfaced in encore, and I thought you might be the best person to ask!

Thanks!

**Comment by ptaoussanis** [comment]
Hi Ravindra,

> I'm sorry if this is the wrong place - but the problem surfaced in encore, and I thought you might be the best person to ask!

No problem, this is definitely the place to ask. Thanks for the detailed report.

Can't think of anything to try off the top of my head; but I feel like I've seen this issue (or something like it) come up before - so need to search my email.

Are you running AOT by any chance?

**Comment by jaju** [comment]
Thanks Peter!

Yes, I have AOT enabled, although I did play with turning it off too. Very interestingly, it had been functioning well all the while before I encountered this all of a sudden. Reverting to various other previous versions of my own code, which had worked well, did not help either. (I tried other versions of Clojure too to make sure it wasn't something peculiar about 1.7.0-RC2. Tried 1.6.0 and 1.7.0-RC1)

Encore is pulled in because of your excellent timbre library - so, I tried explicitly changing to various other prior versions of both timbre and encore (by explicitly depending on it). But that did not help too.

**Comment by ptaoussanis** [comment]
Hi, sorry for the delay replying.

So turning off AOT does _not_ solve this issue? Does it make a difference if you run `lein clean` after disabling AOT?

Can you show me the output from `lein deps :tree`?

Thanks

**Comment by jaju** [comment]
Hi Peter.

I'm very sorry for the delay - have been traveling and could only find time now to try everything afresh. I'm sorry, but I'm unable to reproduce the exception again after turning off AOT. I very distinctly remember turning it off and running a lein clean (and even blowing away my ~/.m2 folder).

Right now, the situation is that with AOT turned off, I do not see the exception, and my REPL starts just fine. With AOT on, the exception happens.

The deps-tree is too big, and may be too noisy for you to go through. As soon as I can, I'll reduce it to the minimum I can which still reproduces the problem and then paste it as a follow-up.

Thank you so much! Appreciate your help here, as well as your generously open-sourced nice libraries!

**Comment by ptaoussanis** [comment]
Closing for now, please feel free to reopen if this is still a problem, cheers! :-)
