### ISSUE TITLE
assert-min-encore-version cannot accept PersistentVector

### ISSUE THREAD

**Issue by chairmanwow** [ptaoussanis/encore#17]
Jars with Carmine LATEST dependencies started dying recently with the following:

#error {
 :cause clojure.lang.PersistentVector cannot be cast to java.lang.Number
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message java.lang.ClassCastException: clojure.lang.PersistentVector cannot be cast to java.lang.Number, compiling:(taoensso/carmine.clj:13:1)
   :at [clojure.lang.Compiler load Compiler.java 7393]}
  {:type java.lang.ClassCastException
   :message clojure.lang.PersistentVector cannot be cast to java.lang.Number
   :at [clojure.lang.Numbers lt Numbers.java 221]}]
 :trace
 [[clojure.lang.Numbers lt Numbers.java 221]
  [taoensso.encore$assert_min_encore_version invokeStatic encore.clj 45]
  [taoensso.encore$assert_min_encore_version invoke encore.clj -1]
  [taoensso.carmine$eval11338 invokeStatic carmine.clj 13]
  [taoensso.carmine$eval11338 invoke carmine.clj -1]

I can't see the bug in github. Did something accidentally get pushed to clojars or something?

FYI, moving Carmine back to 2.12.0-beta1 fixed it, so something seems to have gone south in beta2.

Thanks.

**Comment by chairmanwow** [comment]
FYI, moving Carmine back to 2.12.0-beta1 fixed it, so something seems to have gone south in beta2.

**Comment by ptaoussanis** [comment]
Hi Becker, thanks for the report :+1:! Should be fixed with `[com.taoensso/carmine "2.12.0-beta3"]` (on Clojars now). Cheers! :-)

**Comment by chairmanwow** [comment]
You're a rockstar -- and, thanks for building some awesome Clojure libraries. Nippy and Carmine are fantastic and make our stack possible.

**Comment by ptaoussanis** [comment]
You're very welcome, thanks for saying so! Cheers :-)
