### ISSUE TITLE
2.23.0 somehow breaks custom tag parser

### ISSUE THREAD

**Issue by tuhlmann** [ptaoussanis/encore#18]
Hi,

I'm using sente 1.6.0 and encore 2.20.0 in my project, all works nice (great stuff!!!).
I have registered a custom tag parser with

```
(cljs.reader/register-tag-parser! 'object read-object-id)
```

to parse Mongo's ObjectId into its own structure. There's a similar thing on the Clojure backend that reads `{:$oid "mongo id number"} back into a ObjectId. 

This is custom code- is there maybe a straightforward way to add an already existing ObjectId writer/reader?

Anyway, I get a problem when updating to encore 2.22.0 or 2.23.0. When I do that I get this error thrown in sente's `unpack*`:

```
#error {:message "No reader function for tag object", :data {:type :reader-exception}}
```

I call `register-tag-parser` in my init function, the one that calls `sente/make-channel-socket`.
I see the log statement I put before that call. 

I do understand that encore is kind of an unofficial library, so don't worry if you expect that breakage. If you didn't expect it well, then I hope this bug report is helpful.

Thanks,
Torsten.

**Comment by ptaoussanis** [comment]
> I do understand that encore is kind of an unofficial library, so don't worry if you expect that breakage. 

Hey Torsten, not at all- this was a very helpful report (and an unintended breakage).

Encore v2.1+ swapped from using `cljs.reader` to `cljs.tools.reader` which is probably not inheriting your custom tag parser.

Just have my hands very full atm, but will try get around to taking a look at this soon. If there's no obvious/easy solution, will just drop back to `cljs.reader`.

In the meantime, will you be okay sticking with encore 2.20.0?

**Comment by tuhlmann** [comment]
Thanks, Peter.

I did go back to 2.20.0 and that works fine, no worries.

Thanks,
Torsten.

**Comment by ptaoussanis** [comment]
Okay, have just pushed [com.taoensso/encore "2.24.0"] to Clojars which I believe should fix the problem (untested since I don't use data reader tags myself). Any chance you could give it a try and let me know?

**Comment by tuhlmann** [comment]
Thanks, Peter.

I tested 2.24.0 and 2.26.0. The parser error does not occur anymore, however I'm not facing a different problem which I can't really point a finger to. I'm using secretary and extracting for instance a companyId and then put it into the secretary route. Now for some reasons, with 2.24.0 or 2.26.0 it doesn't extract the id, but instead the url shown in the browser reads `/company/:companyId`. 
I'll need to search a bit to get to the root of it. I keep you posted...

**Comment by ptaoussanis** [comment]
Thanks for the update!

And re: secretary- you've established that it's actually the Encore dependency bump that's causing a problem? (I.e. the exact same code with an older version of encore works okay?).

Just checked & secretary doesn't seem to depend on Encore from what I can tell (or on anything else that does).

**Comment by tuhlmann** [comment]
Ok, did some digging.

It seems the parser I register with `(cljs.reader/register-tag-parser! 'object read-object-id)` is not called.
Instead the ObjectId is layed out as a vector:

```
[org.bson.types.ObjectId 1241723199 "56069c1e2f7515496dab64ef"]
```

There seem to now be some built in mechanism to transform unknown types into this generic form.
Is there any way to hook into this so I can again transform it into a custom format (I user `{:$oid <object-id>}`

**Comment by ptaoussanis** [comment]
Looking into it now, thanks for the helpful debugging info :+1:

**Comment by ptaoussanis** [comment]
Would just like to clarify:

So you're calling `(cljs.reader/register-tag-parser! 'object read-object-id)` to register the `read-object-id` fn as the data reader for the `'object` type.

Then when you try to read one of these objects:

With Encore v2.20.0 (the old one), you got `#object[org.bson.types.ObjectId 0x1c93d832 "560f90172f75156c590dbe56"]` (your intended output).

And now with Encore v2.24.0 (the new one), you get `[org.bson.types.ObjectId 1241723199 "56069c1e2f7515496dab64ef"]` (not your intended output).

Is that correct?

And you're certain that the `read-object-id` fn is not being called for Encore v2.24.0? You've tried a debug println or something in `read-object-id` to confirm that it's not actually running?

**Comment by tuhlmann** [comment]
Thanks for looking into it!

So yes, the format the reader expects is "the old one" (#object...). 
The reader then turns that into `{:$oid <object-id>}`.

Here is my reader, defined in the namespace where the sente-connection is set up:

```
(defn read-object-id [id]
  (log/info "read-object-id")
  (if vector?
    (let [cls (.toString (first id))]
      ;(println "Class is " cls)
      (case cls
        "org.bson.types.ObjectId" {:$oid (.toString (last id))}
        (.toString (last id))))
    (.toString id)))

(log/info "register tag parser")
(cljs.reader/register-tag-parser! 'object read-object-id)
```

I see the "register tag parser" message, but never see a message "read-object-id". I guess the reason is because now the ObjectId is translated into this new vector format and there is now tag `#object` to be recognized by the reader.

Maybe the new mechanism you're using now uses a different reader which in turn uses a different tag parser with different semantics?

**Comment by ptaoussanis** [comment]
Aha, think I've spotted the problem! Give me a sec

**Comment by ptaoussanis** [comment]
Could you try again with `[com.taoensso/encore "2.26.1"]` (just pushed)?

**Comment by tuhlmann** [comment]
I'll do tonight, thanks!

Peter Taoussanis <notifications@github.com> schrieb am Sa., 7. Nov. 2015,
14:34:

**Comment by ptaoussanis** [comment]
Thanks, sorry for the hassle on this.

**Comment by tuhlmann** [comment]
Awesome, super, thanks!

It works now. The reader is called and it creates again my custom ObjectId format.

Thanks for the quick help,
Torsten.

**Comment by ptaoussanis** [comment]
No problem, thanks for being the guinea pig on this :-) Cheers!
