### ISSUE TITLE
merge url with query string error

### ISSUE THREAD

**Issue by dpetrovics** [ptaoussanis/encore#22]
I think this is causing the issue I had with Sente: https://github.com/ptaoussanis/sente/issues/207

`(taoensso.encore/merge-url-with-query-string  "/?foo=bar" {:foo  "overwrite"})` 
=>
`#error {:message "nil as-?qname against arg: :foo", :data {:arg :foo, :type cljs.core/Keyword}}`

**Comment by ptaoussanis** [comment]
Replied at https://github.com/ptaoussanis/sente/issues/207, thanks for the report!
