### ISSUE TITLE
Not compatible with Clojure 1.9.0 Alpha 5!

### ISSUE THREAD

**Issue by seancorfield** [ptaoussanis/encore#25]
Now that `bytes?` is in `clojure.core`, the `defn`-in-`do` used to define it in `taoensso.encore` seems to silently fail, which in turn causes calls to `encore/bytes?` (such as in `taoensso.nippy`) to fail -- because `bytes?` doesn't exist in `encore`.

I'm not sure whether just lifting the `defn` to the top level with fix the problem or whether some sort of version-sensitive gymnastics is going to be required.

Right now, this breaks pretty much the entire taoensso tool chain for us (we use Timbre and Carmine, and were considering Faraday as well).

**Comment by seancorfield** [comment]
The incompatibility doesn't appear to be easy to reproduce. I haven't managed to track down the exact circumstances under which the silent failure of the `defn`-in-`do` occurs. The PR definitely fixes it _for the World Singles project_ but right now I'm not quite sure _why_ it happens in the first place. If I figure out the repro case, I'll update this issue.

**Comment by ptaoussanis** [comment]
Hi Sean, thanks for the report! Will try get a hotfix out for this later today.

**Comment by seancorfield** [comment]
👍

**Comment by ptaoussanis** [comment]
Okay, just pushed `[com.taoensso/encore "2.53.1"]` to Clojars. Could you try insert that into your dependencies before (above) any other taoensso deps and let me know if it resolves the problem?

Just got back from travelling, so haven't had any time to look at Clojure v1.9 myself yet.

Thanks!

**Comment by seancorfield** [comment]
Perfect! 2.53.1 works fine. I'm surprised you can exclude a non-existent symbol in `:refer-clojure` -- with pre-1.9.0 Clojure (which is why I didn't try it). Strange that lifting `defn` out of the `do` also solved the problem (although of course it produces a warning).

**Comment by ptaoussanis** [comment]
Great, thanks for the confirmation Sean!

>  I'm surprised you can exclude a non-existent symbol in :refer-clojure -- with pre-1.9.0 Clojure

Wasn't sure it would work either; was relieved when I saw it did since this may have been tricky to solve properly otherwise.

Cheers :-)
