### ISSUE TITLE
2.82.0 throws warnings on JVM startup

### ISSUE THREAD

**Issue by rationalism** [ptaoussanis/encore#34]
The latest version (2.82.0) of Encore prints these warning messages during JVM startup:

WARNING: Can't take value of macro taoensso.encore/when-not at line 610 file:/home/rationalism/.m2/repository/com/taoensso/encore/2.82.0/encore-2.82.0.jar!/taoensso/encore.cljs
WARNING: Can't take value of macro taoensso.encore/when-not at line 619 file:/home/rationalism/.m2/repository/com/taoensso/encore/2.82.0/encore-2.82.0.jar!/taoensso/encore.cljs
WARNING: Can't take value of macro taoensso.encore/when-not at line 623 file:/home/rationalism/.m2/repository/com/taoensso/encore/2.82.0/encore-2.82.0.jar!/taoensso/encore.cljs
WARNING: Can't take value of macro taoensso.encore/when-not at line 624 file:/home/rationalism/.m2/repository/com/taoensso/encore/2.82.0/encore-2.82.0.jar!/taoensso/encore.cljs
WARNING: Can't take value of macro taoensso.encore/when-not at line 626 file:/home/rationalism/.m2/repository/com/taoensso/encore/2.82.0/encore-2.82.0.jar!/taoensso/encore.cljs
WARNING: Can't take value of macro taoensso.encore/when-not at line 965 file:/home/rationalism/.m2/repository/com/taoensso/encore/2.82.0/encore-2.82.0.jar!/taoensso/encore.cljs

The messages were resolved by downgrading to version 2.81.1.

**Comment by ptaoussanis** [comment]
Hi, thanks for the report! Should be resolved with v2.82.1, now on Clojars. Cheers!
