### ISSUE TITLE
Could not initialize class clojure.tools.reader.edn__init when trying to upgrade to timbre version 4.7.4

### ISSUE THREAD

**Issue by dkincaid** [ptaoussanis/encore#35]
Getting this java.lang.NoClassDefFoundError, Could not initialize class clojure.tools.reader.edn__init when loading my .clj file which requires taoensso/timbre after upgrading to version 4.7.4.

I'm not able to see what the problem might be.

`2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling taoensso/encore.clj at (1:1)

             Compiler.java: 7391  clojure.lang.Compiler/load
                   RT.java:  372  clojure.lang.RT/loadResourceScript
                   RT.java:  363  clojure.lang.RT/loadResourceScript
                   RT.java:  453  clojure.lang.RT/load
                   RT.java:  419  clojure.lang.RT/load
                  core.clj: 5893  clojure.core/load/fn
                  core.clj: 5892  clojure.core/load
                  core.clj: 5876  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5697  clojure.core/load-one
                  core.clj: 5692  clojure.core/load-one
                  core.clj: 5737  clojure.core/load-lib/fn
                  core.clj: 5736  clojure.core/load-lib
                  core.clj: 5717  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  648  clojure.core/apply
                  core.clj: 5774  clojure.core/load-libs
                  core.clj: 5758  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  648  clojure.core/apply
                  core.clj: 5796  clojure.core/require
                  core.clj: 5796  clojure.core/require
               RestFn.java:  457  clojure.lang.RestFn/invoke
                timbre.clj:    1  taoensso.timbre/eval23384/loading--auto--
                timbre.clj:    1  taoensso.timbre/eval23384
                timbre.clj:    1  taoensso.timbre/eval23384
             Compiler.java: 6927  clojure.lang.Compiler/eval
             Compiler.java: 6916  clojure.lang.Compiler/eval
             Compiler.java: 7379  clojure.lang.Compiler/load
                   RT.java:  372  clojure.lang.RT/loadResourceScript
                   RT.java:  363  clojure.lang.RT/loadResourceScript
                   RT.java:  453  clojure.lang.RT/load
                   RT.java:  419  clojure.lang.RT/load
                  core.clj: 5893  clojure.core/load/fn
                  core.clj: 5892  clojure.core/load
                  core.clj: 5876  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5697  clojure.core/load-one
                  core.clj: 5692  clojure.core/load-one
                  core.clj: 5737  clojure.core/load-lib/fn
                  core.clj: 5736  clojure.core/load-lib
                  core.clj: 5717  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  648  clojure.core/apply
                  core.clj: 5774  clojure.core/load-libs
                  core.clj: 5758  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  648  clojure.core/apply
                  core.clj: 5796  clojure.core/require
                  core.clj: 5796  clojure.core/require
               RestFn.java:  512  clojure.lang.RestFn/invoke
           solr_tagger.clj:    1  concept-prevalence.solr-tagger/eval23376/loading--auto--
           solr_tagger.clj:    1  concept-prevalence.solr-tagger/eval23376
           solr_tagger.clj:    1  concept-prevalence.solr-tagger/eval23376
             Compiler.java: 6927  clojure.lang.Compiler/eval
             Compiler.java: 6916  clojure.lang.Compiler/eval
             Compiler.java: 7379  clojure.lang.Compiler/load
                      REPL:    1  concept-prevalence.pipeline/eval23372
                      REPL:    1  concept-prevalence.pipeline/eval23372
             Compiler.java: 6927  clojure.lang.Compiler/eval
             Compiler.java: 6890  clojure.lang.Compiler/eval
                  core.clj: 3105  clojure.core/eval
                  core.clj: 3101  clojure.core/eval
                  main.clj:  240  clojure.main/repl/read-eval-print/fn
                  main.clj:  240  clojure.main/repl/read-eval-print
                  main.clj:  258  clojure.main/repl/fn
                  main.clj:  258  clojure.main/repl
                  main.clj:  174  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  646  clojure.core/apply
                  core.clj: 1881  clojure.core/with-bindings*
                  core.clj: 1881  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
    interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                  AFn.java:   22  clojure.lang.AFn/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  745  java.lang.Thread/run

1. Caused by java.lang.NoClassDefFoundError
   Could not initialize class clojure.tools.reader.edn__init

                Class.java:   -2  java.lang.Class/forName0
                Class.java:  348  java.lang.Class/forName
                   RT.java: 2168  clojure.lang.RT/classForName
                   RT.java: 2177  clojure.lang.RT/classForName
                   RT.java: 2196  clojure.lang.RT/loadClassForName
                   RT.java:  443  clojure.lang.RT/load
                   RT.java:  419  clojure.lang.RT/load
                  core.clj: 5893  clojure.core/load/fn
                  core.clj: 5892  clojure.core/load
                  core.clj: 5876  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5697  clojure.core/load-one
                  core.clj: 5692  clojure.core/load-one
                  core.clj: 5737  clojure.core/load-lib/fn
                  core.clj: 5736  clojure.core/load-lib
                  core.clj: 5717  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  648  clojure.core/apply
                  core.clj: 5774  clojure.core/load-libs
                  core.clj: 5758  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  648  clojure.core/apply
                  core.clj: 5796  clojure.core/require
                  core.clj: 5796  clojure.core/require
               RestFn.java:  551  clojure.lang.RestFn/invoke
                encore.clj:    1  taoensso.encore/eval23392/loading--auto--
                encore.clj:    1  taoensso.encore/eval23392
                encore.clj:    1  taoensso.encore/eval23392
             Compiler.java: 6927  clojure.lang.Compiler/eval
             Compiler.java: 6916  clojure.lang.Compiler/eval
             Compiler.java: 7379  clojure.lang.Compiler/load
                   RT.java:  372  clojure.lang.RT/loadResourceScript
                   RT.java:  363  clojure.lang.RT/loadResourceScript
                   RT.java:  453  clojure.lang.RT/load
                   RT.java:  419  clojure.lang.RT/load
                  core.clj: 5893  clojure.core/load/fn
                  core.clj: 5892  clojure.core/load
                  core.clj: 5876  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5697  clojure.core/load-one
                  core.clj: 5692  clojure.core/load-one
                  core.clj: 5737  clojure.core/load-lib/fn
                  core.clj: 5736  clojure.core/load-lib
                  core.clj: 5717  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  648  clojure.core/apply
                  core.clj: 5774  clojure.core/load-libs
                  core.clj: 5758  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  648  clojure.core/apply
                  core.clj: 5796  clojure.core/require
                  core.clj: 5796  clojure.core/require
               RestFn.java:  457  clojure.lang.RestFn/invoke
                timbre.clj:    1  taoensso.timbre/eval23384/loading--auto--
                timbre.clj:    1  taoensso.timbre/eval23384
                timbre.clj:    1  taoensso.timbre/eval23384
             Compiler.java: 6927  clojure.lang.Compiler/eval
             Compiler.java: 6916  clojure.lang.Compiler/eval
             Compiler.java: 7379  clojure.lang.Compiler/load
                   RT.java:  372  clojure.lang.RT/loadResourceScript
                   RT.java:  363  clojure.lang.RT/loadResourceScript
                   RT.java:  453  clojure.lang.RT/load
                   RT.java:  419  clojure.lang.RT/load
                  core.clj: 5893  clojure.core/load/fn
                  core.clj: 5892  clojure.core/load
                  core.clj: 5876  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5697  clojure.core/load-one
                  core.clj: 5692  clojure.core/load-one
                  core.clj: 5737  clojure.core/load-lib/fn
                  core.clj: 5736  clojure.core/load-lib
                  core.clj: 5717  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  648  clojure.core/apply
                  core.clj: 5774  clojure.core/load-libs
                  core.clj: 5758  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  648  clojure.core/apply
                  core.clj: 5796  clojure.core/require
                  core.clj: 5796  clojure.core/require
               RestFn.java:  512  clojure.lang.RestFn/invoke
           solr_tagger.clj:    1  concept-prevalence.solr-tagger/eval23376/loading--auto--
           solr_tagger.clj:    1  concept-prevalence.solr-tagger/eval23376
           solr_tagger.clj:    1  concept-prevalence.solr-tagger/eval23376
             Compiler.java: 6927  clojure.lang.Compiler/eval
             Compiler.java: 6916  clojure.lang.Compiler/eval
             Compiler.java: 7379  clojure.lang.Compiler/load
                      REPL:    1  concept-prevalence.pipeline/eval23372
                      REPL:    1  concept-prevalence.pipeline/eval23372
             Compiler.java: 6927  clojure.lang.Compiler/eval
             Compiler.java: 6890  clojure.lang.Compiler/eval
                  core.clj: 3105  clojure.core/eval
                  core.clj: 3101  clojure.core/eval
                  main.clj:  240  clojure.main/repl/read-eval-print/fn
                  main.clj:  240  clojure.main/repl/read-eval-print
                  main.clj:  258  clojure.main/repl/fn
                  main.clj:  258  clojure.main/repl
                  main.clj:  174  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  646  clojure.core/apply
                  core.clj: 1881  clojure.core/with-bindings*
                  core.clj: 1881  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
    interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                  AFn.java:   22  clojure.lang.AFn/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  745  java.lang.Thread/run`

**Comment by ptaoussanis** [comment]
Hi David,

Sounds like you're probably experiencing a dependency conflict - please see [here](https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md) for debug steps.

Cheers :-)

**Comment by ptaoussanis** [comment]
Will assume this is resolved, please feel free to reopen if you're still having issues :-)

**Comment by dkincaid** [comment]
Ok. Sorry. I have been really sick for the last few days haven't had the energy to work on much. I'll troubleshoot the dependency conflict and hopefully get it resolved that way.

**Comment by ptaoussanis** [comment]
Oh, no problem - feel free to reopen any time :-) Get some rest, hope you recover soon!

**Comment by dkincaid** [comment]
Still having this same problem after resolving all dependency conflicts. Only one version of encore is being pulled in and only one version of clojure.tools.reader yet it still can't find clojure.tools.reader.edn. 

Here's the relevant section from the lein deps :tree:
` [com.taoensso/encore "2.82.1"]
   [com.taoensso/truss "1.3.6"]
   [org.clojure/tools.reader "0.10.0"]
 [com.taoensso/timbre "4.7.4"]
   [io.aviso/pretty "0.1.30"]
 [com.taoensso/tufte "1.0.2"]
`

all these libraries only appear once. Any ideas what might be going on here?

**Comment by ptaoussanis** [comment]
Hi David,

Almost certainly the case that the wrong dependencies are somehow still finding themselves into your build process. Could be stale built artifacts, some kind of lein profile unexpectedly not/kicking in, an AOT issue, etc.

If you've followed all the steps [here](https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md) without luck, next step would probably be trying something like [lein-pprint](https://github.com/technomancy/leiningen/tree/master/lein-pprint) to confirm that the correct lein profiles are being activated, and then finally perhaps actually checking your build artifacts in your target dir to rule out that the wrong versions are somehow being compiled due to an AOT issue, etc. E.g. some AOT'd lib is pulling in an earlier version of tools.reader.

Best of luck!
