### ISSUE TITLE
Missing `if-cljs` macro

### ISSUE THREAD

**Issue by nasutiooon** [ptaoussanis/encore#46]
Getting this exception when I want to use `taoensso.encore.test/use-fixures`: 

```
Caused by: java.lang.RuntimeException: No such var: taoensso.encore.test/if-cljs
```

It seems because it's not being required

https://github.com/ptaoussanis/encore/blob/master/src/taoensso/encore/test.cljx#L30

```
(ns taoensso.encore.test
  ;; Unfortunately needs to be a separate namespace for now due
  ;; to https://github.com/ptaoussanis/encore/issues/37
  #+clj
  (:require
   [clojure.test    :as test :refer [is]]
   [taoensso.encore :as enc  :refer [have?]])

  #+cljs
  (:require
   [cljs.test       :as test :refer-macros [is]]
   [taoensso.encore :as enc  :refer-macros [have?]]))
```

**Comment by ptaoussanis** [comment]
Thanks for the report, fixed in `v2.106.0`. 👍

**Comment by nasutiooon** [comment]
Was just about to do pull request. Apologies for the slow response!

**Comment by ptaoussanis** [comment]
Oh, no problem at all! I just happened to need to push a new version for other reasons - so figured I'd include this quickly.
