### ISSUE TITLE
goog.structs/Map is deprecated in Closure Library

### ISSUE THREAD

**Issue by roman01la** [ptaoussanis/encore#47]
I was testing the project with ClojureScript master before they publish a new release and noticed the following warning:
```
WARNING: Use of undeclared Var goog.structs/Map at line 2683 target-prod/taoensso/encore.cljs
```

I assume cljs master has updated Closure Library as well.

Looking at Closure docs it says that `Map` struct is deprecated in favor of ES6 `Map` https://google.github.io/closure-library/api/goog.structs.Map.html

**Comment by ptaoussanis** [comment]
Hi Roman, thanks for the report! PR to update welcome 👍

**Comment by ptaoussanis** [comment]
Merged, thank you Roman!
