### ISSUE TITLE
2.126.2 breaks Timbre

### ISSUE THREAD

**Issue by zilti** [ptaoussanis/encore#50]
As the title says, the most recent version breaks Timbre's logging; at the very least the default logging to console. The result is that almost none of the log messages supposed to show up actually do show up on the console anymore. Reverting to 2.122.0 fixes the issue.

**Comment by ptaoussanis** [comment]
@zilti Hi Daniel, thanks for pinging about this.

How sure are you that this happens with `v2.126.2`? Have you tried `lein clean`?
I believe Timbre should work fine with `v2.126.2`, though there was a problem with `v2.123.0` through `v2.125.1`.

See also https://github.com/ptaoussanis/timbre/issues/313, https://github.com/ptaoussanis/timbre/issues/314.

**Comment by zilti** [comment]
I am very sure. I just now updated to `v2.127.0` instead and now I get `partial` log output, but only from a library I use.

**Comment by ptaoussanis** [comment]
> I am very sure. I just now updated to v2.127.0 instead and now I get partial log output, but only from a library I use.

There's zero behaviour changes between `v2.126.2` and `v2.127.0` - you can confirm this by running `git diff v2.126.2 v2.127.0`.

> and now I get partial log output, but only from a library I use

I'm sorry, I'd need more to go on than this.

**Comment by zilti** [comment]
I am not fully sure either - it seems the log output works inside the fulcro library, but as soon as my own code runs after fulcro init, there is no log output. That is actually how it was/is in both `v2.126.2` and `v2.127.0`. I reverted to `v2.122.0` for now, since everything there works as expected.
