### ISSUE TITLE
Proper changelog.md?

### ISSUE THREAD

**Issue by Jarzka** [ptaoussanis/encore#54]
Hi

I would kindly ask you to consider creating a changelog.md file, which contains a list of new features and possibly breaking changes. This kind of file would be important to have when users of the library consider upgrading the current version - to easily see what has been changed between versions.

The current changelog is just a link to commits made to the master. It's way more difficult to understand high level changes there.

**Comment by ptaoussanis** [comment]
@Jarzka Hi Jari,

I'm afraid that this library isn't intended for general audiences. As the README states:

> Please note: this is a library intended mostly for my own use or for advanced users who are comfortable reading the source code to see what's available + how to use it.

On the bright side, if you're using it as a transient dependency- the library is always backwards compatible (so you can+should always include the latest version, without fear of breakages).

Choice to exclude a CHANGELOG is a conscious trade-off. I still have a lot of code that I'd like to publish as open source, and limited time. I modify Encore quite frequently (again, non-breaking changes)- and by minimizing the maintenance burden here, I can spend more time on libraries intended for general audiences.

Hope that helps, at least a little.

Cheers!
