### ISSUE TITLE
Clojure 1.11 preparations  - abs

### ISSUE THREAD

**Issue by ieugen** [ptaoussanis/encore#59]
Hi, 

Got this warning upgrading to clojure 1.11.0-rc1:

```
; WARNING: abs already refers to: #'clojure.core/abs in namespace: taoensso.encore, being replaced by: #'taoensso.encore/abs
```

**Comment by ptaoussanis** [comment]
Hi Eugene, please ensure that you're using the latest version of Encore - see [here](https://github.com/ptaoussanis/encore/pull/58).

Cheers! :-)
