### ISSUE TITLE
`dis-assoc-some` with multiple args doesn't dissoc first key

### ISSUE THREAD

**Issue by zohar-cyc** [ptaoussanis/encore#62]
Calling `dis-assoc-some` with multiple pairs uses `assoc-some ` as the initial value, instead of itself. 
So if the first value is nil, the first key keeps its previous value instead of being `dissoc`d
```clojure
(encore/dis-assoc-some {:a 1 :b 2} :a nil)
=> {:b 2}
(encore/dis-assoc-some {:a 1 :b 2} :a nil :b 3)
=> {:a 1, :b 3}
```

**Comment by ptaoussanis** [comment]
@zohar-cyc Hi Zohar, thanks for the report!
Now fixed in `[com.taoensso/encore "3.24.0"]` 👍
